name: 'Close PR replacement'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - closed

jobs:
  changes-strings:
    if: github.event.pull_request.merged == true
    runs-on: "ubuntu-latest"
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git config
        run: |
          git config --global user.mail "corleone77daniel@gmail.com"
          git config --global user.name "Cor77"

      - name: Execution Bash Script
        env:
          SOURCE: "${{ vars.SOURCE }}"
          TARGET: "${{ vars.TARGET }}"
          ENVIRONT: "${{ vars.ENVIRONMET_STAGE }}"
        run: |
          echo "$SOURCE"
          echo "$TARGET"
          echo "$ENVIRONT"
          .scripts/substitution.sh $SOURCE $TARGET

      - name: Commit and Push
        env:
          ENV_STAGE: ${{ vars.ENVIRONMET_STAGE }}
        run: |
          GIT_STATUS=$(git status)
          if [[ $GIT_STATUS ]]; then
            git add ./replacement
            git commit -m "Replacement of variables $ENV_STAGE"
            git pull origin $ENV_STAGE
          fi

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_PAT }}
          force: true
