name: 'Close PR replacement'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - uat
      
  pull_request:
    types:
      - opened
      - closed

jobs:
  changes-strings:
    if: github.event.pull_request.merged == true
    runs-on: "ubuntu-latest"
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Execution Bash Script
        env:
          SOURCE: "${{ vars.SOURCE }}"
          TARGET: "${{ vars.TARGET }}"
          ENVIRONT: "${{ vars.ENVIRONMET_STAGE }}"
        run: |
          echo "$SOURCE"
          echo "$TARGET"
          echo "$ENVIRONT"
          .scripts/substitution.sh $SOURCE $TARGET

      - name: Commit changes
        run: |
            GIT_STATUS=$(git status)
            echo $ENV_STAGE
            if [[ $GIT_STATUS ]]; then
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git commit -a -m "Make changes to the code in the $ENV_STAGE"
            fi

      - name: Push changes to ${{github.action_ref}} branch
        uses: ad-m/github-push-action@master
        env:
          ENVIRONMENT: "${{ vars.ENVIRONMET_STAGE }}"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.action_ref }}

      #- name: Commit and Push
      #  env:
      #    ENV_STAGE: ${{ vars.ENVIRONMET_STAGE }}
      #  run: |
      #    git config  --global user.name "cor77"
      #    git config --global user.mail "corleone1977@protonmail.com"
      #    GIT_STATUS=$(git status)
      #    echo $ENV_STAGE
      #    if [[ $GIT_STATUS ]]; then
      #      git add ./replacement
      #      git commit -m "Replacement of variables $ENV_STAGE"
      #      git pull origin ${ENV_STAGE}
      #    fi

