name: 'Link Checker: All English'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - edited
      - opened
      - closed

jobs:
  check-links:
    runs-on: "ubuntu-latest"
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show files changed
        run: echo 'Hola Mundo'

      - name: Execution Bash Script
        env:
          SOURCE: ${{ vars.SOURCE }}
          TARGET: ${{ vars.TARGET }}
        run: |
          pwd
          .scripts/substitution.sh $SOURCE $TARGET

      - name: Commit and Push
        run: |
          GIT_STATUS=$(git status)
          if [[ $GIT_STATUS ]]; then
            git config user.email github-actions@github.com
            git add .
            git config user.name cor77
            git commit -m "Replacement of variables"
            git pull origin ${{ github.base_ref }}
          else
            echo "Don't changes detected"
          fi
