name: 'Close PR replacement'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - edited
      - opened
      - closed

jobs:
  check-links:
    runs-on: "ubuntu-latest"
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git config
        run: |
          git config --global user.mail "no-reply@github.com"
          git config --global user.name "Actions service account"

      - name: Execution Bash Script
        env:
          SOURCE: "${{ vars.SOURCE }}"
          TARGET: "${{ vars.TARGET }}"
          ENVIRONT: "${{ vars.ENVIRONMET_STAGE }}"
        run: |
          echo "$SOURCE"
          echo "$TARGET"
          echo "$ENVIRONMET_STAGE"
          pwd
          .scripts/substitution.sh $SOURCE $TARGET

      - name: Commit and Push
        env:
          ENV_STAGE: ${{vars.ENVIRONMET_STAGE}}
        run: |
          GIT_STATUS=$(git status)
          if [[ $GIT_STATUS ]]; then
<<<<<<< HEAD
            git add ./replacement
            git commit -m "Replacement of variables"
            git pull origin ${{ github.base_ref }}
=======
            git config user.email github-actions@github.com
            git add .
            git config user.name cor77
            git commit -m "Replacement of variables"
            git pull origin ${{ github.base_ref }}
          else
            echo "Don't changes detected"
>>>>>>> 41db99a (new variables branch dev)
          fi
